defaults:
  - /slam: default

instance: vipe.pipeline.panorama.PanoramaAnnotationPipeline

# Init configs
init:
  instance:
    kf_gap_sec: 2.0
    phrases: 
      - person
      - animal
      - vehicle
      - ball
      - balloon
      - gun
      - pet
      - car
      - bus
    add_sky: false

virtual:
  height: 512
  fovx: 100.0
  fovy: 100.0
  num_views: 4
  top: false
  bottom: true

slam:
  buffer: 256
  optimize_intrinsics: false
  keyframe_depth: null
  map_filter_thresh: 0.01

post:
  depth_align_model: null

# Output configs
output:
  # Path to save results
  path: vipe_results/
  skip_exists: false

  # Save artifacts and a info file
  save_artifacts: false

  # Visualization videos to BASE_PATH/vipe/xxx.mp4
  save_viz: true
  viz_downsample: 2
  viz_attributes: [["rgb"], ["pcd"], ["instance"]]
